openapi: 3.1.0
info:
  title: TypeScript Express API Template
  description: This is a template for a TypeScript Express API
  version: 0.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /status:
    get:
      summary: Get server status
      description: Detailed description of the endpoint
      responses:
        "200":
          description: Successful response
        "404":
          description: Resource not found
components:
  schemas:
    YourSchemaName:
      type: object
      properties:
        propertyName:
          type: string
      required:
        - propertyName
